apiVersion: v1
kind: Template
labels:
  template: fedora-generic-check-worker
metadata:
  annotations:
    description: Fedora generic-check-worker container
  name: fedora-generic-check-worker-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: fedora-generic-check-worker
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: fedora-generic-check-worker
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: fedora-generic-check-worker:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: fedora-generic-check-worker
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://pagure.io/fedora-ci-generic-checks.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/s2i/fedora-generic-check-worker/
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
